### ISSUE TITLE
Fix background image setting

### ISSUE THREAD

**Issue by ingvar1995** [pkrasicki/SyncPaint#2]
Hello! There is a bug with adding background image in current master

**Actual behavior:** Adding background image adds it behind actual white canvas. 
**Expected behavior:** Adding background image adds it above actual white canvas. 

:smiley:

**Comment by pkrasicki** [comment]
Hi! That was done on purpose to allow users to draw over the background and be able to use an eraser without erasing the background image. Background is a second layer that you can draw on top of. By default the background layer is fully transparent and foreground layer is white. I will have to think of a better way to do this.
