### ISSUE TITLE
Need Clarity on a piece of code

### ISSUE THREAD

**Issue by iamprincesuman** [pkrasicki/SyncPaint#39]
In public -> draw.html file, line number 7 says <script src="/socket.io/socket.io.js"></script> but i am not able to locate this file..
help me in this issue

**Comment by pkrasicki** [comment]
This file is served by the socket.io server, so if you have the backend running, you should be able to access it in your browser. It's described here in the documentation: https://socket.io/docs/v2/client-installation/#installation

**Comment by iamprincesuman** [comment]
whenever i am trying to do npm install node modules folder get deleted automatically.. need help .. :(

**Comment by iamprincesuman** [comment]
what is ./dist file.. pls help..

**Comment by pkrasicki** [comment]
Please paste the output of `npm install`.

What version of Node.js do you have? You can check it with command `node --version`.

`dist` is a folder that contains compiled frontend files after running `npm run build`.
