### ISSUE TITLE
Possible Docker container?

### ISSUE THREAD

**Issue by tscibilia** [pkrasicki/SyncPaint#6]
Would you consider a docker container for easy deployment? I'm not skilled at doing it, I made an attempt but I can't get the build to complete. If anyone has any experience/input please let me know. 

https://github.com/tscibilia/syncpaint/blob/master/Dockerfile

[Here's the build log from docker](https://hastebin.com/ofulituqal.makefile)

**Comment by pkrasicki** [comment]
Added in https://github.com/pkrasicki/SyncPaint/pull/7!
